### ISSUE TITLE
nginx コンフィグのアップデート

### ISSUE THREAD

**Issue by yakitama** [bluenapoleon/mastodon#32]
nginx のキャッシュに関する設定がアップデートされたらしいので、次のアップデートのときに忘れずに更新すること。

**Comment by YaQ00** [comment]
やった？ @yakitama

**Comment by yakitama** [comment]
忘れてた。

**Comment by yakitama** [comment]
サーバーを AWS → VPS に移設したときに nginx コンフィグをアップデートしていました。対応完了。
